CREATE SEQUENCE IF NOT EXISTS empleados_clave_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS empleados (
    clave VARCHAR(32) PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    direccion VARCHAR(100) NOT NULL,
    telefono VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_empleados_nombre ON empleados (nombre);
